apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-u5hw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-u5hw
    app.kubernetes.io/part-of: ci10t-786-0100-app
  name: devfile-sample-u5hw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-u5hw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-u5hw
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0100-tenant/ci10t-786-0100-app/devfile-sample-u5hw@sha256:f60bb091b16ea6958c58552b50544a05b24a699f7ed7d1b2eccc7c233610100c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
